import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import dashboardRouter from "./dashboard.js";
import categoriesRouter from "./categories.js";
import brandsRouter from "./brands.js";
import unitsRouter from "./units.js";
import productsRouter from "./products.js";
import customersRouter from "./customers.js";
import craftsmenRouter from "./craftsmen.js";
import suppliersRouter from "./suppliers.js";
import quotationsRouter from "./quotations.js";
import salesRouter from "./sales.js";
import purchasesRouter from "./purchases.js";
import stockRouter from "./stock.js";
import debtsRouter from "./debts.js";
import draftsRouter from "./drafts.js";
import reportsRouter from "./reports.js";
import settingsRouter from "./settings.js";
import backupRouter from "./backup.js";
import returnsRouter from "./returns.js";
import usersRouter from "./users.js";
import expensesRouter from "./expenses.js";
import deletePreviewRouter from "./delete-preview.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(dashboardRouter);
router.use(categoriesRouter);
router.use(brandsRouter);
router.use(unitsRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(craftsmenRouter);
router.use(suppliersRouter);
router.use(quotationsRouter);
router.use(salesRouter);
router.use(returnsRouter);
router.use(purchasesRouter);
router.use(stockRouter);
router.use(debtsRouter);
router.use(draftsRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(backupRouter);
router.use(expensesRouter);
router.use(deletePreviewRouter);

export default router;
